"""_proto.py – _TypeCheckerBase

Mixin 間で共有されるインスタンス変数とメソッドシグネチャを宣言する基底クラス。
各 Mixin がこのクラスを継承することで、Pylance が cross-Mixin の self.xxx 参照をエラーなく解決できるようになる。
実際の実装は MRO 上の TypeChecker および各 Mixin が提供する。
"""
from __future__ import annotations
from typing import Any
from Ast import TypeNode, FunctionDecl, StructDecl


class _TypeCheckerBase:
    """型ヒント用インターフェース宣言。実装は各 Mixin と TypeChecker が提供する。"""

    # ------------------------------------------------------------------
    # インスタンス変数 (TypeChecker.__init__ で初期化される)
    # ------------------------------------------------------------------
    structs:     dict[str, StructDecl]  # name -> StructDecl
    functions:   dict[str, FunctionDecl]  # name -> FunctionDecl
    enums:       dict[str, Any]         # name -> EnumDecl
    env:         list[dict[str, Any]]   # スコープスタック（辞書のリスト）
    const_table: dict[str, Any]         # name -> {type, expr}
    fix_vars:    set[str]               # fix 宣言された不変変数名のセット

    # ------------------------------------------------------------------
    # 型比較・置換 (TypeChecker.__init__.py 実装)
    # ------------------------------------------------------------------
    def types_equal(self, a: TypeNode, b: TypeNode) -> bool: ...
    def substitute_type(self, t: TypeNode, subst: dict[str, Any]) -> TypeNode: ...
    def find_common_numeric_type(self, a: TypeNode, b: TypeNode) -> TypeNode: ...
    def numeric_type_rank(self, type_name: str) -> int: ...
    def is_signed_int(self, type_name: str) -> bool: ...
    def is_unsigned_int(self, type_name: str) -> bool: ...

    # ------------------------------------------------------------------
    # 変数参照・スコープ (_expr.py 実装)
    # ------------------------------------------------------------------
    def lookup_var(self, name: str, expr: Any) -> TypeNode: ...
    def _pattern_bindings_scope(self, pattern: Any) -> dict[str, TypeNode]: ...
    def is_integer_type(self, type_name: str) -> bool: ...
    def is_float_type(self, type_name: str) -> bool: ...
    def is_numeric_type(self, type_name: str) -> bool: ...

    # ------------------------------------------------------------------
    # 式チェック (_expr.py 実装)
    # ------------------------------------------------------------------
    def check_expr(self, expr: Any) -> TypeNode: ...
    def check_binary(self, expr: Any) -> TypeNode: ...
    def check_unary(self, expr: Any) -> TypeNode: ...
    def check_lambda(self, expr: Any) -> TypeNode: ...
    def check_await(self, expr: Any) -> TypeNode: ...
    def check_weak(self, expr: Any) -> TypeNode: ...
    def check_array_access(self, expr: Any) -> TypeNode: ...
    def check_array_literal(self, expr: Any) -> TypeNode: ...

    # ------------------------------------------------------------------
    # 文チェック (_stmt.py 実装)
    # ------------------------------------------------------------------
    def check_block(self, block: Any, expected_return_type: Any) -> None: ...
    def check_statement(self, stmt: Any, expected_return_type: Any) -> None: ...
    def check_let(self, stmt: Any) -> None: ...
    def check_fix(self, stmt: Any) -> None: ...
    def check_const_decl(self, stmt: Any) -> None: ...
    def check_conditional_block(self, stmt: Any, expected_return_type: Any) -> None: ...
    def check_assignment(self, stmt: Any) -> None: ...
    def check_if(self, stmt: Any, expected_return_type: Any) -> None: ...
    def check_while(self, stmt: Any, expected_return_type: Any) -> None: ...
    def check_for(self, stmt: Any, expected_return_type: Any) -> None: ...
    def check_return(self, stmt: Any, expected_return_type: Any) -> None: ...

    # ------------------------------------------------------------------
    # 呼び出し・ジェネリクス (_call.py 実装)
    # ------------------------------------------------------------------
    def check_struct_init(self, expr: Any) -> TypeNode: ...
    def check_struct_access(self, expr: Any) -> TypeNode: ...
    def check_method_call(self, expr: Any) -> TypeNode: ...
    def check_call(self, expr: Any) -> TypeNode: ...
    def check_call_non_generic(self, expr: Any, func: FunctionDecl) -> TypeNode: ...
    def _check_iter_method(self, expr: Any, elem_type: TypeNode) -> TypeNode: ...
    def _check_observable_method(self, expr: Any, obj_type: TypeNode) -> TypeNode: ...
